channels:
  # Define conda channels here.
  - conda-forge

dependencies:
  # Define conda packages here.
  # If available, always prefer the conda version of a package.
  # Installation will be faster and more efficient.
  # https://anaconda.org/search
  - python=3.11.2               # https://pyreadiness.org/3.9/ 

  - pip=23.3.1                    # https://pip.pypa.io/en/stable/news/
  - pip:
      # Define pip packages here.
      # https://pypi.org/
      - rpaframework==27.7.0    # https://rpaframework.org/releasenotes.html